(function(){var base="/DinkFlixWatchLater",items=[],recs=[],cat="all";
function token(){try{var c=JSON.parse(localStorage.getItem("jellyfin_credentials")||"{}"),s=c.Servers||[];for(var i=0;i<s.length;i++)if(s[i].AccessToken)return s[i].AccessToken}catch(e){}return""}
function api(u,o){o=o||{};o.headers=o.headers||{};var t=token();if(t)o.headers["X-Emby-Token"]=t;return fetch(u,o).then(function(r){if(!r.ok)return r.text().then(function(x){throw Error(x||("HTTP "+r.status))});return r.status===204?null:r.json()})}
function img(p,s){return p?"https://image.tmdb.org/t/p/"+s+p:""}
function err(m){var e=document.getElementById("error");e.textContent=m;e.hidden=false}
function card(x,rec){var c=document.createElement("article");c.className="card";var im=document.createElement("img");im.src=img(x.posterPath,"w500");im.alt=x.title;c.appendChild(im);var d=document.createElement("div"),t=document.createElement("div");t.className="title";t.textContent=x.title;d.appendChild(t);var m=document.createElement("div");m.className="meta";m.textContent=x.mediaType==="tv"?"TV Show":"Movie";d.appendChild(m);var a=document.createElement("div");a.className="actions";
if(rec){var b=document.createElement("button");b.className="request";b.textContent="Save";b.onclick=function(){b.disabled=true;b.textContent="Saving...";api(base+"/items",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tmdbId:x.tmdbId,mediaType:x.mediaType})}).then(load).catch(function(e){b.disabled=false;b.textContent="Save";err(e.message)})};a.appendChild(b);d.appendChild(a);c.appendChild(d);return c}
var p=document.createElement("button");p.className="request";p.textContent="Checking...";p.disabled=true;var r=document.createElement("button");r.textContent="Remove";r.onclick=function(){r.disabled=true;api(base+"/items/"+x.tmdbId+"?mediaType="+encodeURIComponent(x.mediaType),{method:"DELETE"}).then(load).catch(function(e){r.disabled=false;err(e.message)})};a.appendChild(p);a.appendChild(r);d.appendChild(a);c.appendChild(d);
api(base+"/availability/"+x.tmdbId+"?mediaType="+x.mediaType).then(function(v){if(v.availableOnJellyfin){p.textContent="Play";p.className="play";p.disabled=false;p.onclick=function(){location.href="/web/#/details?id="+v.jellyfinItemId}}else if(v.seerrStatus!=="unknown"){p.textContent=v.seerrStatus.replace(/_/g," ")}else{p.textContent="Request";p.className="request";p.disabled=false;p.onclick=function(){p.disabled=true;p.textContent="Requesting...";api(base+"/request/"+x.tmdbId,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mediaType:x.mediaType})}).then(function(){p.textContent="Requested"}).catch(function(e){p.disabled=false;p.textContent="Request";err(e.message)})}}}).catch(function(){p.textContent="Status unavailable"});return c}
function render(){var saved=document.getElementById("saved"),rs=document.getElementById("recs"),g=document.getElementById("grid"),rg=document.getElementById("recGrid");g.innerHTML="";rg.innerHTML="";
if(cat==="recommendations"){saved.hidden=true;rs.hidden=false;document.getElementById("recEmpty").hidden=recs.length>0;recs.forEach(function(x){rg.appendChild(card(x,true))});return}
saved.hidden=false;rs.hidden=true;var f=cat==="all"?items:items.filter(function(x){return x.category===cat});document.getElementById("empty").hidden=f.length>0;document.getElementById("count").textContent=f.length+" title"+(f.length===1?"":"s");document.getElementById("heading").textContent=cat==="movie"?"Movies":cat==="tv"?"TV Shows":cat==="anime"?"Anime":"Everything saved";f.forEach(function(x){g.appendChild(card(x,false))})}
function load(){document.getElementById("error").hidden=true;return Promise.all([api(base+"/items"),api(base+"/recommendations").catch(function(){return[]})]).then(function(x){items=x[0]||[];recs=x[1]||[];render()}).catch(function(e){err(e.message)})}
document.getElementById("tabs").onclick=function(e){var b=e.target.closest("button");if(!b)return;document.querySelectorAll("#tabs button").forEach(function(x){x.classList.remove("active")});b.classList.add("active");cat=b.dataset.cat;render()};
document.getElementById("searchForm").onsubmit=function(e){e.preventDefault();var q=document.getElementById("search").value.trim();if(q.length<2)return;var box=document.getElementById("results");box.hidden=false;box.innerHTML="<p>Searching Seerr...</p>";api(base+"/search?query="+encodeURIComponent(q)).then(function(rs){box.innerHTML="";rs.forEach(function(x){var c=document.createElement("article");c.className="result";var im=document.createElement("img");im.src=img(x.posterPath,"w185");c.appendChild(im);var d=document.createElement("div"),b=document.createElement("b");b.textContent=x.title;d.appendChild(b);var s=document.createElement("small");s.textContent=x.mediaType==="tv"?"TV SHOW":"MOVIE";d.appendChild(s);var a=document.createElement("button");a.textContent=x.isSaved?"Saved":"Add to Watch Later";a.disabled=x.isSaved;a.onclick=function(){a.disabled=true;a.textContent="Saving...";api(base+"/items",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tmdbId:x.tmdbId,mediaType:x.mediaType})}).then(function(){a.textContent="Saved";load()}).catch(function(e){a.disabled=false;a.textContent="Add to Watch Later";err(e.message)})};d.appendChild(a);c.appendChild(d);box.appendChild(c)})}).catch(function(e){err(e.message)})};load()})();
