using System;using System.Collections.Generic;using System.Linq;using System.Security.Claims;using System.Threading.Tasks;using Jellyfin.Data.Enums;using Jellyfin.Plugin.DinkFlixWatchLater.Api.Dto;using Jellyfin.Plugin.DinkFlixWatchLater.Services;using MediaBrowser.Controller.Entities;using MediaBrowser.Controller.Library;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace Jellyfin.Plugin.DinkFlixWatchLater.Api;
[ApiController][Authorize][Route("DinkFlixWatchLater")]public class WatchLaterController:ControllerBase{
const string Claim="Jellyfin-UserId";readonly WatchLaterStore store;readonly SeerrClient seerr;readonly ILibraryManager library;
public WatchLaterController(WatchLaterStore store,SeerrClient seerr,ILibraryManager library){this.store=store;this.seerr=seerr;this.library=library;}
bool TryGetUserId(out string id){id=HttpContext.User.FindFirst(Claim)?.Value??HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value??"";return !string.IsNullOrWhiteSpace(id);}
[HttpGet("items")]public async Task<ActionResult<IEnumerable<WatchLaterItemDto>>> Items(){if(!TryGetUserId(out var id))return Unauthorized();var x=await store.GetItemsAsync(id);return Ok(x.OrderByDescending(a=>a.AddedAtUtc));}
[HttpPost("items")]public async Task<ActionResult<WatchLaterItemDto>> Add([FromBody]AddItemRequest r){if(!TryGetUserId(out var uid))return Unauthorized();if(r.TmdbId<=0)return BadRequest("Invalid TMDB ID.");var type=r.MediaType=="tv"?"tv":"movie";try{var m=type=="tv"?await seerr.GetTvAsync(r.TmdbId):await seerr.GetMovieAsync(r.TmdbId);if(m is null)return NotFound("Seerr could not resolve the title.");var item=new WatchLaterItemDto{TmdbId=r.TmdbId,MediaType=type,Title=m.Title??m.Name??"Unknown title",PosterPath=m.PosterPath,BackdropPath=m.BackdropPath,OriginalLanguage=m.OriginalLanguage,Genres=m.Genres?.Select(g=>g.Name).ToList()??[],AddedAtUtc=DateTime.UtcNow};await store.AddItemAsync(uid,item);return Ok(item);}catch(Exception e){return StatusCode(502,"Seerr error: "+e.Message);}}
[HttpDelete("items/{tmdbId:int}")]public async Task<ActionResult> Remove(int tmdbId,[FromQuery]string mediaType="movie"){if(!TryGetUserId(out var id))return Unauthorized();await store.RemoveItemAsync(id,tmdbId,mediaType);return NoContent();}
[HttpGet("search")]public async Task<ActionResult<IEnumerable<SearchResultDto>>> Search(string query){if(!TryGetUserId(out var uid))return Unauthorized();if(string.IsNullOrWhiteSpace(query)||query.Trim().Length<2)return Ok(Array.Empty<SearchResultDto>());try{var saved=(await store.GetItemsAsync(uid)).Select(x=>$"{x.MediaType}:{x.TmdbId}").ToHashSet(StringComparer.OrdinalIgnoreCase);var r=await seerr.SearchAsync(query);var list=r?.Results.Where(x=>x.Id>0).Select(x=>new SearchResultDto{TmdbId=x.Id,MediaType=x.Type,Title=x.DisplayTitle,PosterPath=x.Poster,BackdropPath=x.Backdrop,OriginalLanguage=x.Language,IsSaved=saved.Contains($"{x.Type}:{x.Id}")}).GroupBy(x=>$"{x.MediaType}:{x.TmdbId}").Select(x=>x.First()).Take(24).ToList()??[];return Ok(list);}catch(Exception e){return StatusCode(502,"Seerr search failed: "+e.Message);}}
[HttpGet("recommendations")]public async Task<ActionResult<IEnumerable<SearchResultDto>>> Recommendations(){if(!TryGetUserId(out var uid))return Unauthorized();try{var saved=await store.GetItemsAsync(uid);var keys=saved.Select(x=>$"{x.MediaType}:{x.TmdbId}").ToHashSet(StringComparer.OrdinalIgnoreCase);var output=new List<SearchResultDto>();foreach(var s in saved.OrderByDescending(x=>x.AddedAtUtc).Take(6)){foreach(var x in await seerr.RecommendationsAsync(s.TmdbId,s.MediaType)){var key=$"{x.Type}:{x.Id}";if(x.Id>0&&!keys.Contains(key))output.Add(new SearchResultDto{TmdbId=x.Id,MediaType=x.Type,Title=x.DisplayTitle,PosterPath=x.Poster,BackdropPath=x.Backdrop,OriginalLanguage=x.Language});}if(output.Count>=24)break;}return Ok(output.GroupBy(x=>$"{x.MediaType}:{x.TmdbId}").Select(x=>x.First()).Take(24));}catch(Exception e){return StatusCode(502,"Seerr recommendations failed: "+e.Message);}}
[HttpGet("test-connection")][AllowAnonymous]public async Task<ActionResult<object>> TestConnection(){return Ok(new{connected=await seerr.TestConnectionAsync()});}
[HttpGet("availability/{tmdbId:int}")]public async Task<ActionResult<AvailabilityDto>> Availability(int tmdbId,[FromQuery]string mediaType="movie"){var r=new AvailabilityDto();var q=new InternalItemsQuery{HasAnyProviderId=new Dictionary<string,string>{{"Tmdb",tmdbId.ToString()}},IncludeItemTypes=mediaType=="tv"?new[]{BaseItemKind.Series}:new[]{BaseItemKind.Movie}};var jf=library.GetItemList(q).FirstOrDefault();if(jf is not null){r.AvailableOnJellyfin=true;r.JellyfinItemId=jf.Id.ToString("N");}try{var m=mediaType=="tv"?await seerr.GetTvAsync(tmdbId):await seerr.GetMovieAsync(tmdbId);r.SeerrStatus=m?.MediaInfo?.Status switch{2=>"pending",3=>"processing",4=>"partially_available",5=>"available",_=>"unknown"};}catch{r.SeerrStatus="unknown";}r.CanRequest=!r.AvailableOnJellyfin&&r.SeerrStatus=="unknown";return Ok(r);}
[HttpPost("request/{tmdbId:int}")]public async Task<ActionResult> RequestItem(int tmdbId,[FromBody]RequestItemRequest r){try{return await seerr.RequestMediaAsync(tmdbId,r.MediaType=="tv"?"tv":"movie")?Ok():StatusCode(502,"Seerr rejected the request.");}catch(Exception e){return StatusCode(502,"Seerr request failed: "+e.Message);}}
static readonly string Root=typeof(Plugin).Namespace!;static readonly Dictionary<string,string> Assets=new(StringComparer.OrdinalIgnoreCase){{"watchlater.css","text/css"},{"watchlater.js","application/javascript"}};
[HttpGet("web/page")][AllowAnonymous]public ActionResult Page(){var s=GetType().Assembly.GetManifestResourceStream($"{Root}.Web.watchlater.html");return s is null?NotFound():File(s,"text/html");}
[HttpGet("web/{fileName}")][AllowAnonymous]public ActionResult Asset(string fileName){if(!Assets.TryGetValue(fileName,out var t))return NotFound();var s=GetType().Assembly.GetManifestResourceStream($"{Root}.Web.{fileName}");return s is null?NotFound():File(s,t);}
}
