<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><AssemblyName>Jellyfin.Plugin.DinkFlixWatchLater</AssemblyName><RootNamespace>Jellyfin.Plugin.DinkFlixWatchLater</RootNamespace><Version>1.1.0.0</Version><NoWarn>CA1848;CA2007</NoWarn></PropertyGroup><ItemGroup><PackageReference Include="Jellyfin.Controller" Version="12.0.0"><ExcludeAssets>runtime</ExcludeAssets></PackageReference><PackageReference Include="Jellyfin.Model" Version="12.0.0"><ExcludeAssets>runtime</ExcludeAssets></PackageReference></ItemGroup><ItemGroup><EmbeddedResource Include="Configuration\configPage.html"/><EmbeddedResource Include="Web\watchlater.html"/><EmbeddedResource Include="Web\watchlater.css"/><EmbeddedResource Include="Web\watchlater.js"/></ItemGroup></Project>
